### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by peter279k** [MetamorphPHP/metamorph#6]
As title, I think it's important because other developers don't want to set the `dev-master` version in `composer.json` for their projects :+1:.

**Comment by iampersistent** [comment]
Yeah, fair enough. I don't want to go to a v1 yet, because there might still be breakage, but I did tag it v0.1.

Thanks for the suggestion.

**Comment by peter279k** [comment]
@iampersistent, thank you for your reply.

It's ok to tag the `v0.1` version. And thank you for your help.
